root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["start"]
  bin = "tmp/app"
  cmd = "go build -o ./tmp/app ."
  delay = 3500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "resources", "output", "debug_output", "node_modules", "frontend", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = true
  full_bin = ""
  include_dir = [".", "../../pkg"]
  include_ext = ["go"]
  include_file = []
  kill_delay = "0s"
  log = "tmp/build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = true
  rerun_delay = 1000
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true