# Help target

.PHONY: help

help:
	@echo "Available targets:"
	@echo "  all         - Build everything (default)"
	@echo "  generate-templates - Generate tmpl.go from templates/"
	@echo "  generate-schemas - Generate Zod schemas from TypeScript types"
	@echo "  build-ts-sdk- Build TypeScript SDK"
	@echo "  build-vue-ui- Build Vue UI library"
	@echo "  docs-install- Install swag tool"
	@echo "  clean-schemas - Clean only generated schemas"
	@echo "  regen-schemas - Force regenerate schemas"
	@echo "  fmt         - Format Go code with gofmt -s"
	@echo "  lint        - Run golangci-lint"
	@echo "  lint-install- Install golangci-lint"
	@echo "  install-hooks - Install Git pre-push hook for test verification"
	@echo "  dev-services - Start development support services (Redis, MailHog, SMSHog)"
	@echo "  dev-services-down - Stop development support services"
	@echo "  demo-backend - Run demo backend with hot reload (auto-starts dev-services)"
	@echo "  demo-frontend - Run demo frontend with hot reload (auto-builds if needed)"
	@echo "  dev-e2e     - Run E2E tests against local dev environment"
	@echo "  test        - Run tests in tests/ directory (default: SQLite)"
	@echo "  test-mysql  - Run tests with MySQL configuration"
	@echo "  test-pgsql  - Run tests with PostgreSQL configuration"
	@echo "  test-custom - Run tests with custom configuration file"
	@echo "  e2e-up      - Start E2E environment (PostgreSQL + Redis + Backend + Frontend)"
	@echo "  e2e-down    - Stop E2E environment"
	@echo "  e2e-test    - Run E2E tests"
	@echo "  e2e-logs    - View E2E environment logs"
	@echo "  e2e-full    - Full E2E workflow (up + test + down)"
	@echo "  clean       - Clean all generated files and build artifacts"
	@echo ""
	@echo "Usage examples:"
	@echo "  make test                    # Run tests with SQLite (default)"
	@echo "  make test-mysql              # Run tests with MySQL"
	@echo "  make test-pgsql              # Run tests with PostgreSQL"
	@echo "  make test-custom CONF_FILE=my.conf  # Run tests with custom config"
	@echo "  CONF_FILE=mysql.conf make test     # Direct environment variable"
	@echo "  make e2e-up                  # Start E2E environment"
	@echo "  make e2e-test                # Run E2E tests"
	@echo "  make e2e-full                # Complete E2E test cycle"
	@echo ""
	@echo "File targets:"
	@echo "  docs/specs/auth-api.json  - Generate auth API documentation"
	@echo "  docs/specs/admin-api.json - Generate admin API documentation"
	@echo "  packages/slauth-ts/src/types/auth-api.ts - Generate auth types"
	@echo "  packages/slauth-ts/src/types/admin-api.ts - Generate admin types"

